Optional skip param for FileNet_SendFile
Batfoxkid/File-Network pull request #5
Opened 2023-04-15 19:02 UTC by Nolo001-Aha

Lets plugin authors choose whether they want File Network to query sv_allowupload in FileNet_SendFile or not. Can be rather useful in cases where plugins relying on File Network have their own cvar query implementations, and having a 2nd one would complicate the logic. (For example, my solution needs FileNetwork to queue the file as fast as possible without any timers and additional queries involved, I check cvars before I get to send/request anything).

2023-04-16 04:01 UTC, Batfoxkid reviewed
I think I'll be more in for removing the sv_allowupload check itself. Very niche use case of having it in here and would be more appropriate that it'll return a fail when it client rejects it.

2023-04-16 09:39 UTC, Nolo001-Aha commented
If I'm not mistaken, even with cl_allowupload set to 0 (I _think_ cl_allowupload is the correct ConVar, as **cl** stands for client and that's what clients can use to toggle uploading custom content to servers; sv_allowupload is the server-side ConVar that acts as a global on-off switch whether clients are allowed to upload stuff or not) clients fully receive the file but then discard it once the file is reconstructed.

Pretty sure it's ok to go straight for Timer_SendingClient then, without the ConVar query. Would you like me to pr that?

2023-04-17 01:40 UTC, Batfoxkid commented
> If I'm not mistaken, even with cl_allowupload set to 0 (I _think_ cl_allowupload is the correct ConVar, as **cl** stands for client and that's what clients can use to toggle uploading custom content to servers; sv_allowupload is the server-side ConVar that acts as a global on-off switch whether clients are allowed to upload stuff or not) clients fully receive the file but then discard it once the file is reconstructed.
> 
> Pretty sure it's ok to go straight for Timer_SendingClient then, without the ConVar query. Would you like me to pr that?

Yeah, just skipping the ConVar query will be best.

2023-04-17 11:27 UTC, Nolo001-Aha commented
Should be fine now I think

2023-04-17 16:15 UTC, Batfoxkid requested changes

2023-04-17 16:15 UTC, Batfoxkid commented on scripting/include/filenetwork.inc
> +native bool FileNet_SendFile(int client, const char[] file, FileNet_SendFileResult callback = INVALID_FUNCTION, any data = 0, bool skip = false);
This change is still present.

2023-04-17 16:44 UTC, Nolo001-Aha commented on scripting/include/filenetwork.inc
> +native bool FileNet_SendFile(int client, const char[] file, FileNet_SendFileResult callback = INVALID_FUNCTION, any data = 0, bool skip = false);
Done, how blind can I get...

2023-04-18 05:55 UTC, y0edan commented
Can't seem to get the plugin running and keep getting the following error;

L 04/18/2023 - 00:52:38: [SM] Exception reported: [Gamedata] EngineInterface is incorrect for mod
L 04/18/2023 - 00:52:38: [SM] Blaming: core/filenetwork.smx
L 04/18/2023 - 00:52:38: [SM] Call stack trace:
L 04/18/2023 - 00:52:38: [SM]   [0] SetFailState
L 04/18/2023 - 00:52:38: [SM]   [1] Line 99, plugin.sp::OnPluginStart

CS:GO - 
 DHooks (1.11.0.6930) by AlliedModders LLC: Dynamic Hooks
 SourceMod 1.11.0.6930, by AlliedModders LLC
 
 Any ideas?

2023-04-18 19:02 UTC, y0edan commented
Thank you!! Will test tonight.

2023-04-21 18:51 UTC, closed without merging